### PR TITLE
Fix typo.

### PR DESCRIPTION
**Pull request by jmhobbs**
Had a typo on the github page.  :)

### CODE REVIEW

**Comment by zachleat** [comment]
@jmhobbs please remerge from master :-)

**Comment by zachleat** [comment]
IS THIS EVEN BEING MAINTAINED

OPEN SOURCE GUILT

**Comment by jmhobbs** [comment]
:crying_cat_face:

**Comment by jmhobbs** [comment]
OH YES

**Comment by dleatherman** [comment]
back-on-track

**Pull request merged**
